### PR TITLE
Add new skins

### PR DESCRIPTION
**Pull request by visiongirles**
Add new skins: Duck, Evil Duck, Owl and Nyan

### CODE REVIEW

**Review by visiongirles — COMMENTED** [review]
Add Duck, Evil Duck, Owl and Nyan skins

**Comment by inferst** [comment]
@visiongirles

Thank you for such impressive skins!

If you don't mind I'll create Aseprite sources from your sprites.
It's really convenient to work with Aseprite, especially with animations, highly recommend.

Also I've found some missing pixels. If you don't mind I would like to do some fixes and update your PR.

**Comment by visiongirles** [comment]
@inferst please feel free to make any modification including, but not limited, the ones you mentioned. Thank you!

**Comment by inferst** [comment]
@visiongirles successfully merged and deployed!

**Pull request merged**
